FROM node:21.7.0-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG ci_build
ARG VITE_BLOCKS_API_URL
ARG VITE_API_BASE_URL
ARG VITE_DATA_GATEWAY_URL
ARG VITE_GRAPHQL_ENDPOINT
ARG VITE_X_BLOCKS_KEY
ARG X_BLOCKS_KEY
ARG SELISE_X_BLOCKS_KEY
ARG VITE_SELISE_BLOCKS_KEY
ARG SELISE_BLOCKS_KEY
ARG VITE_SELISE_PROJECT_KEY
ARG SELISE_PROJECT_KEY
ARG PROJECT_KEY
ARG BLOCKS_KEY
ARG VITE_CAPTCHA_SITE_KEY
ARG VITE_CAPTCHA_TYPE
ARG VITE_PROJECT_SLUG
ARG PROJECT_SLUG
ARG VITE_SELISE_APP_DOMAIN
ARG SELISE_APP_DOMAIN
ARG APP_DOMAIN

ENV VITE_BLOCKS_API_URL=${VITE_BLOCKS_API_URL}
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_DATA_GATEWAY_URL=${VITE_DATA_GATEWAY_URL}
ENV VITE_GRAPHQL_ENDPOINT=${VITE_GRAPHQL_ENDPOINT}
ENV VITE_X_BLOCKS_KEY=${VITE_X_BLOCKS_KEY}
ENV X_BLOCKS_KEY=${X_BLOCKS_KEY}
ENV SELISE_X_BLOCKS_KEY=${SELISE_X_BLOCKS_KEY}
ENV VITE_SELISE_BLOCKS_KEY=${VITE_SELISE_BLOCKS_KEY}
ENV SELISE_BLOCKS_KEY=${SELISE_BLOCKS_KEY}
ENV VITE_SELISE_PROJECT_KEY=${VITE_SELISE_PROJECT_KEY}
ENV SELISE_PROJECT_KEY=${SELISE_PROJECT_KEY}
ENV PROJECT_KEY=${PROJECT_KEY}
ENV BLOCKS_KEY=${BLOCKS_KEY}
ENV VITE_CAPTCHA_SITE_KEY=${VITE_CAPTCHA_SITE_KEY}
ENV VITE_CAPTCHA_TYPE=${VITE_CAPTCHA_TYPE}
ENV VITE_PROJECT_SLUG=${VITE_PROJECT_SLUG}
ENV PROJECT_SLUG=${PROJECT_SLUG}
ENV VITE_SELISE_APP_DOMAIN=${VITE_SELISE_APP_DOMAIN}
ENV SELISE_APP_DOMAIN=${SELISE_APP_DOMAIN}
ENV APP_DOMAIN=${APP_DOMAIN}

RUN mkdir -p /app/log

RUN NODE_OPTIONS="--max-old-space-size=4096" npm run build:${ci_build}

FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
