server {
  root /usr/share/nginx/html/;
  server_tokens off;
  client_max_body_size 200m;
  large_client_header_buffers 8 32k;
  gzip             on;
  gzip_comp_level  6;
  gzip_min_length  1000;
  gzip_proxied     expired no-cache no-store private auth;
  gzip_types       text/plain application/x-javascript text/xml text/css application/xml text/javascript application/javascript application/json application/font-woff application/font-woff2 application/vnd.ms-fontobject application/x-font-ttf font/opentype;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /blocks-api/idp/v1/Authentication/Token {
    proxy_pass https://api.seliseblocks.com/idp/v1/Authentication/Token;
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_ssl_name api.seliseblocks.com;
    proxy_set_header Host api.seliseblocks.com;
    proxy_set_header Connection "";
    proxy_set_header Cookie "";
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 30s;
    proxy_send_timeout 120s;
    proxy_read_timeout 120s;
    proxy_buffer_size 64k;
    proxy_buffers 16 64k;
    proxy_busy_buffers_size 128k;
    proxy_cookie_domain api.seliseblocks.com $host;
    proxy_cookie_domain .seliseblocks.com $host;
    proxy_cookie_path / /;
  }

  location /blocks-api/ {
    proxy_pass https://api.seliseblocks.com/;
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_ssl_name api.seliseblocks.com;
    proxy_set_header Host api.seliseblocks.com;
    proxy_set_header Connection "";
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 30s;
    proxy_send_timeout 120s;
    proxy_read_timeout 120s;
    proxy_buffer_size 64k;
    proxy_buffers 16 64k;
    proxy_busy_buffers_size 128k;
    proxy_cookie_domain api.seliseblocks.com $host;
    proxy_cookie_domain .seliseblocks.com $host;
    proxy_cookie_path / /;
  }
}
